ALTER TABLE bookings
    ADD CONSTRAINT uk_bookings_business_id UNIQUE (business_id, id);

CREATE TABLE booking_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_booking_history_booking_tenant
        FOREIGN KEY (business_id, booking_id)
        REFERENCES bookings (business_id, id),
    CONSTRAINT fk_booking_history_actor
        FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT ck_booking_history_from_status CHECK (
        from_status IS NULL OR from_status IN (
            'PENDING', 'CONFIRMED', 'CANCELLED',
            'REJECTED', 'COMPLETED', 'NO_SHOW'
        )
    ),
    CONSTRAINT ck_booking_history_to_status CHECK (
        to_status IN (
            'PENDING', 'CONFIRMED', 'CANCELLED',
            'REJECTED', 'COMPLETED', 'NO_SHOW'
        )
    )
);

CREATE INDEX idx_booking_history_booking_created
    ON booking_status_history (booking_id, created_at);
