ALTER TABLE services
    ADD COLUMN booking_mode VARCHAR(30) NOT NULL DEFAULT 'EXCLUSIVE_RESOURCE';

ALTER TABLE services
    ADD CONSTRAINT ck_service_booking_mode CHECK (
        booking_mode IN ('EXCLUSIVE_RESOURCE', 'CAPACITY_SESSION')
    );

ALTER TABLE offering_resources
    ADD CONSTRAINT uk_offering_resource_tenant
        UNIQUE (business_id, service_id, location_id, resource_id);

CREATE TABLE capacity_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    capacity_total INTEGER NOT NULL,
    capacity_reserved INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_capacity_session_natural
        UNIQUE (service_id, resource_id, starts_at),
    CONSTRAINT uk_capacity_session_tenant
        UNIQUE (business_id, location_id, service_id, resource_id, id),
    CONSTRAINT fk_capacity_session_offering_resource
        FOREIGN KEY (business_id, service_id, location_id, resource_id)
        REFERENCES offering_resources (
            business_id, service_id, location_id, resource_id
        ),
    CONSTRAINT ck_capacity_session_interval CHECK (starts_at < ends_at),
    CONSTRAINT ck_capacity_session_total CHECK (capacity_total > 0),
    CONSTRAINT ck_capacity_session_reserved CHECK (
        capacity_reserved >= 0 AND capacity_reserved <= capacity_total
    ),
    CONSTRAINT ck_capacity_session_status CHECK (
        status IN ('OPEN', 'CANCELLED')
    )
);

CREATE INDEX idx_capacity_sessions_availability
    ON capacity_sessions (service_id, location_id, starts_at, status);

ALTER TABLE bookings
    ADD COLUMN capacity_session_id BIGINT;

ALTER TABLE bookings DROP CONSTRAINT ck_booking_quantity;

ALTER TABLE bookings
    ADD CONSTRAINT ck_booking_quantity CHECK (quantity > 0);

ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_capacity_session
        FOREIGN KEY (
            business_id, location_id, service_id, resource_id, capacity_session_id
        )
        REFERENCES capacity_sessions (
            business_id, location_id, service_id, resource_id, id
        );

ALTER TABLE bookings
    ADD CONSTRAINT ck_booking_capacity_shape CHECK (
        (capacity_session_id IS NULL AND quantity = 1)
        OR capacity_session_id IS NOT NULL
    );
