ALTER TABLE businesses
    ADD COLUMN rating_average NUMERIC(3, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE businesses
    ADD COLUMN rating_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE businesses
    ADD CONSTRAINT ck_business_rating_average CHECK (
        rating_average BETWEEN 0.00 AND 5.00
    );

ALTER TABLE businesses
    ADD CONSTRAINT ck_business_rating_count CHECK (rating_count >= 0);

ALTER TABLE bookings
    ADD CONSTRAINT uk_bookings_review_identity
        UNIQUE (business_id, id, customer_id);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    comment VARCHAR(1000),
    verified BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_review_booking UNIQUE (booking_id),
    CONSTRAINT fk_review_booking_customer
        FOREIGN KEY (business_id, booking_id, customer_id)
        REFERENCES bookings (business_id, id, customer_id),
    CONSTRAINT fk_review_business
        FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT ck_review_score CHECK (score BETWEEN 1 AND 5),
    CONSTRAINT ck_review_verified CHECK (verified)
);

CREATE INDEX idx_reviews_business_created
    ON reviews (business_id, created_at DESC);
