CREATE TABLE business_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    role VARCHAR(50) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    invited_by_user_id BIGINT NOT NULL,
    accepted_by_user_id BIGINT,
    accepted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_invitation_business
        FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_invitation_inviter
        FOREIGN KEY (invited_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_invitation_acceptor
        FOREIGN KEY (accepted_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_invitation_role CHECK (role IN ('OWNER', 'ADMIN', 'STAFF')),
    CONSTRAINT ck_invitation_status CHECK (
        status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')
    ),
    CONSTRAINT ck_invitation_acceptance CHECK (
        (status = 'ACCEPTED' AND accepted_by_user_id IS NOT NULL AND accepted_at IS NOT NULL)
        OR
        (status <> 'ACCEPTED' AND accepted_by_user_id IS NULL AND accepted_at IS NULL)
    )
);

CREATE INDEX idx_invitations_business_status
    ON business_invitations (business_id, status, created_at);

CREATE INDEX idx_invitations_email_status
    ON business_invitations (email, status);

CREATE INDEX idx_memberships_business_active_role
    ON business_memberships (business_id, active, role);
