CREATE TABLE business_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_membership_business_user UNIQUE (business_id, user_id),
    CONSTRAINT fk_membership_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_membership_role CHECK (role IN ('OWNER', 'ADMIN', 'STAFF'))
);

CREATE INDEX idx_memberships_user_active
    ON business_memberships (user_id, active);

INSERT INTO business_memberships (
    business_id, user_id, role, active, created_at, updated_at
)
SELECT
    business_id,
    id,
    CASE WHEN role = 'ADMIN' THEN 'ADMIN' ELSE 'STAFF' END,
    active,
    created_at,
    updated_at
FROM users
WHERE business_id IS NOT NULL;
