CREATE TABLE business_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    address VARCHAR(250) NOT NULL,
    city VARCHAR(120) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    timezone VARCHAR(60) NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(9, 6) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_business_location_name UNIQUE (business_id, name),
    CONSTRAINT fk_location_business FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT ck_location_country_code CHECK (CHAR_LENGTH(country_code) = 2),
    CONSTRAINT ck_location_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_location_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_locations_business_active
    ON business_locations (business_id, active);

CREATE INDEX idx_locations_coordinates
    ON business_locations (latitude, longitude);
