CREATE TABLE resource_schedule_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    rule_type VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_resource_schedule_rule
        UNIQUE (resource_id, day_of_week, rule_type, start_time, end_time),
    CONSTRAINT fk_schedule_rule_business
        FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_schedule_rule_resource_tenant
        FOREIGN KEY (business_id, location_id, resource_id)
        REFERENCES resources (business_id, location_id, id),
    CONSTRAINT ck_schedule_rule_day CHECK (
        day_of_week IN (
            'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
            'FRIDAY', 'SATURDAY', 'SUNDAY'
        )
    ),
    CONSTRAINT ck_schedule_rule_type CHECK (rule_type IN ('AVAILABLE', 'BREAK')),
    CONSTRAINT ck_schedule_rule_time CHECK (start_time < end_time)
);

CREATE INDEX idx_schedule_rules_resource_day
    ON resource_schedule_rules (resource_id, day_of_week, start_time);

CREATE TABLE resource_schedule_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    exception_date DATE NOT NULL,
    exception_type VARCHAR(20) NOT NULL,
    start_time TIME,
    end_time TIME,
    reason VARCHAR(250),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_resource_exception_date UNIQUE (resource_id, exception_date),
    CONSTRAINT fk_schedule_exception_business
        FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_schedule_exception_resource_tenant
        FOREIGN KEY (business_id, location_id, resource_id)
        REFERENCES resources (business_id, location_id, id),
    CONSTRAINT ck_schedule_exception_type CHECK (
        exception_type IN ('CLOSED', 'CUSTOM_HOURS')
    ),
    CONSTRAINT ck_schedule_exception_values CHECK (
        (exception_type = 'CLOSED' AND start_time IS NULL AND end_time IS NULL)
        OR
        (
            exception_type = 'CUSTOM_HOURS'
            AND start_time IS NOT NULL
            AND end_time IS NOT NULL
            AND start_time < end_time
        )
    )
);

CREATE INDEX idx_schedule_exceptions_resource_date
    ON resource_schedule_exceptions (resource_id, exception_date);
