CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    notes VARCHAR(500),
    idempotency_key VARCHAR(100) NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_booking_customer_idempotency
        UNIQUE (customer_id, idempotency_key),
    CONSTRAINT fk_booking_business
        FOREIGN KEY (business_id) REFERENCES businesses (id),
    CONSTRAINT fk_booking_customer
        FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_booking_service_location
        FOREIGN KEY (business_id, service_id, location_id)
        REFERENCES offering_locations (business_id, service_id, location_id),
    CONSTRAINT fk_booking_resource_tenant
        FOREIGN KEY (business_id, location_id, resource_id)
        REFERENCES resources (business_id, location_id, id),
    CONSTRAINT ck_booking_interval CHECK (starts_at < ends_at),
    CONSTRAINT ck_booking_quantity CHECK (quantity = 1),
    CONSTRAINT ck_booking_status CHECK (
        status IN (
            'PENDING', 'CONFIRMED', 'CANCELLED',
            'REJECTED', 'COMPLETED', 'NO_SHOW'
        )
    ),
    CONSTRAINT ck_booking_cancellation CHECK (
        (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
        OR (status <> 'CANCELLED')
    )
);

CREATE INDEX idx_bookings_resource_time
    ON bookings (resource_id, starts_at, ends_at);

CREATE INDEX idx_bookings_customer_created
    ON bookings (customer_id, created_at);

CREATE INDEX idx_bookings_business_time
    ON bookings (business_id, starts_at, status);
